import { NextResponse } from "next/server";

export async function POST(request: Request) {
  const { topic, content } = await request.json();
  const text = String(content ?? "");
  const words = text.toLowerCase().replace(/[^a-z0-9\s]/g, "").split(/\s+/).filter(Boolean);
  const freq = new Map<string, number>();
  for (const w of words) {
    if (w.length < 5) continue;
    freq.set(w, (freq.get(w) ?? 0) + 1);
  }
  const keywords = [...freq.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8).map(([k]) => k);

  return NextResponse.json({
    topic,
    keywords,
    summary: `This brief explains ${topic}. Main ideas include ${keywords.slice(0, 4).join(", ")}.`,
    revisionNotes: keywords.map((k, i) => `${i + 1}. Understand how ${k} impacts ${topic}.`),
    citationDraft: `${topic}. (2026). Working draft generated by ProdigyOS AI Copilot.`,
    podcastScript: `Welcome to your ProdigyOS research recap on ${topic}. Today we cover ${keywords.join(", ")}.`
  });
}
